import { normalizeIban } from './ibanUtils.js';

// Line order per the Swiss "Style Guide QR-bill" (SIX/SPC v2.x) payload format embedded in a
// Swiss QR-Bill's QR code. Only the lines this parser actually reads are named; everything else
// (detailed creditor/debtor address lines, the still-reserved "Ultimate Creditor" block) is
// skipped over. Cross-checked against a real payload generated by the `swissqrbill` library in
// qrBillScan.test.js — if that test disagrees with the field extraction here, these indices are
// what's wrong.
const LINE = {
  HEADER: 0,
  IBAN: 3,
  CREDITOR_NAME: 5,
  AMOUNT: 18,
  CURRENCY: 19,
  REFERENCE_TYPE: 27,
  REFERENCE: 28,
};
const MIN_LINES = 31;
const EXPECTED_HEADER = 'SPC';

export function parseQrBillPayload(text) {
  if (!text) return null;
  const zeilen = text.split(/\r\n|\r|\n/);
  if (zeilen.length < MIN_LINES) return null;
  if (zeilen[LINE.HEADER].trim() !== EXPECTED_HEADER) return null;

  // normalizeIban also strips internal whitespace, not just leading/trailing — out-of-spec but
  // real-world QR-bill generators can emit grouping spaces in the IBAN line, and leaving them in
  // would make this never equal the space-stripped IBANs stored via the admin route, producing a
  // false IBAN-mismatch fraud alert against a legitimate invoice.
  const iban = normalizeIban(zeilen[LINE.IBAN]);
  if (!iban) return null;

  const referenzTyp = zeilen[LINE.REFERENCE_TYPE].trim();
  const referenz = zeilen[LINE.REFERENCE].trim();
  const betrag = zeilen[LINE.AMOUNT].trim();
  const waehrung = zeilen[LINE.CURRENCY].trim();
  const creditorName = zeilen[LINE.CREDITOR_NAME].trim();

  return {
    iban,
    creditorName: creditorName || null,
    betrag: betrag || null,
    waehrung: waehrung || null,
    referenz: referenzTyp !== 'NON' && referenz ? referenz : null,
  };
}
